Add a simulation script
fdcl-data-driven-control/DataDrivenControl.jl pull request #18
Opened 2021-12-31 11:28 UTC by JinraeKim

Resolves #10 (partially).

Note: #14 에서 이어짐.

동역학을 돌리기 위한 스크립트 예제를 작성했습니다.

아직 linear IRL 로 업데이트한 것은 아니고, [1, example 2] 의 예제 시스템을 구현하고 확인한 것입니다.
향후 linear IRL 의 업데이트를 [DiscreteCallback](https://diffeq.sciml.ai/stable/features/callback_functions/#DiscreteCallback-Examples) 을 이용해서 적용하면 될 것으로 보입니다.

아래 그림은 파라미터를 논문 상의 최적값으로 넣은 상태에서의 response 입니다.
![image](https://user-images.githubusercontent.com/43136096/147820926-c6e000cb-1154-4ac8-a9db-09c772a17b31.png)

# Refs
[1] “Reinforcement Learning and Feedback Control: Using Natural Decision Methods to Design Optimal Adaptive Controllers,” IEEE Control Syst., vol. 32, no. 6, pp. 76–105, Dec. 2012, doi: 10.1109/MCS.2012.2214134.

2022-01-03 13:12 UTC, JinraeKim commented
#14 Rebased

2022-01-05 12:52 UTC, JinraeKim commented
#22 rebased

2022-01-05 13:33 UTC, hnlee77 requested changes

2022-01-05 13:33 UTC, hnlee77 commented on src/utils/stop_conditions/stop_conditions.jl
> +function is_stopped(sc::AbstractStopCondition, args...; kwrags...)
`is_stopped`가 뭔가 와닿지 않아서 ㅎㅎ `is_converged` 같은 이름은 어때요?

2022-01-05 13:33 UTC, hnlee77 commented on src/irl/linear_irl.jl
> +    stopped::Bool
```suggestion
    converged::Bool
```

2022-01-05 13:33 UTC, hnlee77 commented on src/irl/linear_irl.jl
> +        stopped = false
```suggestion
        converged = false
```

2022-01-05 13:33 UTC, hnlee77 commented on src/irl/linear_irl.jl
> +                irl.stopped = true
```suggestion
            if is_converged(sc, w, w_new)
                irl.converged = true
```

2022-01-05 13:33 UTC, hnlee77 commented on src/irl/linear_irl.jl
> +                irl.stopped = true
```suggestion
        if !irl.converged
            if is_converged(sc, w, w_new)
                irl.converged = true
```

2022-01-05 13:33 UTC, hnlee77 commented on src/utils/stop_conditions/stop_conditions.jl
> +function is_stopped(sc::AbstractStopCondition, args...; kwrags...)
```suggestion
function is_converged(sc::AbstractStopCondition, args...; kwrags...)
```

2022-01-05 13:33 UTC, hnlee77 commented on src/utils/stop_conditions/stop_conditions.jl
> +function is_stopped(sc::DistanceStopCondition, w, w_new)
```suggestion
function is_converged(sc::DistanceStopCondition, w, w_new)
```

2022-01-05 15:06 UTC, JinraeKim commented
@hnlee77 `stopped` -> `converged` 리뷰에 대한 답변:

`is_stopped` 보다 `is_terminated` 가 좀 더 나을듯.

별개로 "converged" 를 쓰지 않는 이유는, stop condition 이 꼭 수렴조건이지 않을 수 있기 때문임.

2022-01-07 04:49 UTC, hnlee77 approved these changes
굳. 코드 아주 깔끔하네요. 저도 이렇게 짜고 싶음.

2022-01-07 05:00 UTC, JinraeKim commented
> 굳. 코드 아주 깔끔하네요. 저도 이렇게 짜고 싶음.

ㅋㅋㅋㅋㅋㅋ 그럼 #20 한번 이렇게 짜보실?

2022-01-07 05:00 UTC, merged

2022-01-07 05:05 UTC, hnlee77 commented
오케!

2022-01-07 05:06 UTC, JinraeKim commented
> 오케!

올 ㅎㅎ
그럼 #20 이 현재 #24 에 이미 작업중이긴 한데, 다시 얘기를 해서 파트를 나누던가 할까요?

2022-01-07 05:51 UTC, hnlee77 commented
> > 오케!
> 
> 올 ㅎㅎ 그럼 #20 이 현재 #24 에 이미 작업중이긴 한데, 다시 얘기를 해서 파트를 나누던가 할까요?

좋아요~ 얘기 가능할 때 불러주세욥